BanTien/BanTien/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanTien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DanhGiaTiens = new HashSet<DanhGiaTien>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaTien { get; set; }
        public string TenTien { get; set; }
        public string MoTaTien { get; set; }
        public string TheLoai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string AnhMinhHoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaTien> DanhGiaTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LoaiTien LoaiTien { get; set; }
    }
}

BanTien/BanTien/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanTien.Models;

namespace BanTien.Controllers
{
    public class SanPhamsController : Controller
    {
        private BANTIENEntities db = new BANTIENEntities();

        // GET: SanPhams
        public ActionResult Index(string searchString)
        {
            var listKH = db.SanPhams.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                var links = db.SanPhams.Where(s => s.MaTien.ToString().Contains(searchString)
                                        || s.TenTien.Contains(searchString));
                return View(links.ToList());
            }
            else
                return View(listKH);

        }



        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.TheLoai = new SelectList(db.LoaiTiens, "MaLoai", "TenLoai");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTien,TenTien,TacGia,NhaXuatBan,NgayXuatBan,TheLoai,SoLuong,DonGia,AnhMinhHoa")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TheLoai = new SelectList(db.LoaiTiens, "MaLoai", "TenLoai", sanPham.TheLoai);

            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.TheLoai = new SelectList(db.LoaiTiens, "MaLoai", "TenLoai", sanPham.TheLoai);

            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTien,TenTien,TacGia,NhaXuatBan,NgayXuatBan,TheLoai,SoLuong,DonGia,AnhMinhHoa")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TheLoai = new SelectList(db.LoaiTiens, "MaLoai", "TenLoai", sanPham.TheLoai);
      
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BanTien/BanTien/Views/SanPhams/Create.cshtml
@model BanTien.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Home.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TheLoai, "TheLoai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TheLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TheLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhMinhHoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhMinhHoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhMinhHoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BanTien/BanTien/Views/SanPhams/Delete.cshtml
@model BanTien.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhMinhHoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhMinhHoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiTien.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTien.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BanTien/BanTien/Views/SanPhams/Details.cshtml
@model BanTien.Models.SanPham
@using BanTien.Models
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Home.cshtml";

    string role = "";
    int id = 0;
    BANTIENEntities db = new BANTIENEntities();
    List<DanhGiaTien> danhgia = new List<DanhGiaTien>();
    if (User.Identity.IsAuthenticated)
    {
        role = (from u in db.TaiKhoans
                where u.Username == User.Identity.Name.ToString()
                select u.Role).FirstOrDefault();
        id = (from u in db.KhachHangs
              where u.UsernameKH == User.Identity.Name.ToString()
              select u.MaKH).FirstOrDefault();
    }
    danhgia = (from u in db.DanhGiaTiens
               where u.MaTien == Model.MaTien
               select u).ToList();
    bool check = db.DanhGiaTiens.Any(x => x.MaKH == id && x.MaTien == Model.MaTien);
}

<div class="main">
    <div class="product-img">
        <span><img src="@Model.AnhMinhHoa" /></span>
    </div>
    <div class="product-info">
        <h3>@Model.TenTien</h3>
        <p><label>Thể loại:</label> @Model.LoaiTien.TenLoai</p>
        <p>
           
            {
                <span>&lt;Chưa cập nhật&gt;</span>
            }
            else
            {
               
            }
        </p>
        @if (role == "admin")
        {
            <p><label>Trong kho:</label> <span style="color:blue;">@Model.SoLuong</span></p>
            <button id="update" onclick="location.href = '@Url.Action("Edit", "SanPhams", new { id = Model.MaTien})'"><i class="glyphicon glyphicon-pencil"></i> Chỉnh sửa</button>
        }
        else
        {
            <p>
                <label>Tình trạng:</label>
                @if (Model.SoLuong.Value > 0)
                {
                    <span>Còn hàng</span>
                }
                else
                {
                    <span style="color:red;">Tạm thời hết hàng</span>
                }
            </p>
            <h2 style="color:red;">@Model.DonGia.Value.ToString("0#,0") đồng</h2>
            <form action="/GioHang/AddItem" method="post" id="add">
                <input type="number" id="quantity" name="quantity" min="1" max="5" value="1" />
                <input id="MaTien" name="MaTien" value="@Model.MaTien" style="display:none;" />
                <input id="MaKH" name="MaKH" value="@id" style="display:none;" />
                <input name="action" value="Details/@Model.MaTien" style="display:none;" />
                <input name="controller" value="SanPhams" style="display:none;" />
                <button type="submit" id="buy"><i class="glyphicon glyphicon-shopping-cart"></i></button>
            </form>
        }

    </div>
</div>

<div class="product-review">
    <div class="review-head">
        <h3>Đánh giá sản phẩm</h3>
        <div style="display:flex;">
            @if (role == "user")
            {
                if (!check)
                {
                    <form action="/DanhGia/Add" method="post" id="post-review">
                        <input type="text" name="review" width="200" id="write" />
                        <input name="id_khach" value="@id" style="display:none;" />
                        <input name="id_sach" value="@Model.MaTien" style="display:none;" />
                        <button id="add-review" type="submit">Thêm bình luận</button>
                    </form>
                }
                else
                {
                    <p id="notify">*Lưu ý: mỗi khách hàng chỉ bình luận mỗi sản phẩm 1 lần</p>
                    <form action="/DanhGia/Delete" method="post" onsubmit="return confirm('Bạn chắc muốn xóa bình luận chứ?');">
                        <input name="id_khach" value="@id" style="display:none;" />
                        <input name="id_sach" value="@Model.MaTien" style="display:none;" />
                        <button id="del-review" type="submit">Xóa bình luận</button>
                    </form>
                }
            }
        </div>
    </div>
    <div class="review-items">
        @if(danhgia == null || danhgia.Count == 0)
        {
            <label id="no-review">Chưa có đánh giá</label>
        }
        else
        {
            foreach(var item in danhgia)
            {
                <div class="review-item">
                    <div id="review-account">
                        <h4>@item.KhachHang.UsernameKH</h4><span>&ensp;@item.ThoiGianDang.Value.ToString("dd-MM-yyyy HH:mm")&ensp;</span>
                        @if (role == "admin")
                        {
                            <form action="/DanhGia/Delete" method="post" onsubmit="return confirm('Xác nhận xóa?');">
                                <input name="id_khach" value="@item.MaKH" style="display:none;" />
                                <input name="id_sach" value="@Model.MaTien" style="display:none;" />
                                <button id="admin-delete" type="submit">Xóa</button>
                            </form>
                        }
                    </div>
                    <p>@item.NoiDungDanhGia</p>
                </div>
            }
        }
    </div>
</div>
<style>
    #post-review{
        width:50%;
        display:flex;
        justify-content:space-between;
    }
    #write{
        font-weight:normal;
        min-width:300px;
    }
    footer{
        display:none;
    }
    #review-account{
        display:flex;
    }
    #admin-delete{
        color:red;
        display:inline;
        background-color:transparent;
        border:none;
    }
    .review-item{
        margin-top: 5px;
        width:100%;
        height:70px;
        padding:10px;
        border:1px solid black;
        border-radius:5px;
    }
    .review-item h4{
        color:blue;
        margin:0;
    }
    .review-item p{
        background-color:antiquewhite;
        padding-left:10px;
    }
    #no-review{
        font-family:cursive;
        color:gray;
        padding:10px;
        font-size:18px;
    }
    .body-container{
        display:block;
    }
    .product-info{
        width:60%;
        padding: 20px 10px 20px 50px;
        font-family:'Times New Roman';
        font-size:16px;
        color:black;
    }
    .product-img{
        width:40%;
    }
    .product-info h3{
        color:blue;
    }
    .product-info p label {
        color: #868484;
    }
    .product-info form button,
    #update{
        border:0;
        border-radius:0;
        background-color:black;
        color:white;
        width:28px;
        height:28px;
        outline:0;
    }
    #update {
        width: 100px;
        height: 40px;
    }
        .product-info form button:hover,
        .product-info form button:focus,
        #update:hover,
        #update:focus{
            background-color: white;
            color: black;
        }
        .product-img span {
            margin: 0 auto;
        }
    .product-img img {
        width: 100%;
        height: 100%;
        border: 1px solid #d5caca;
        border-radius:5px;
        padding:20px 20px;
    }
    .main {
        width: 70%;
        height: 400px;
        margin: 20px auto;
        border: 1px solid #f1f1f1;
        display: flex;
    }
        .main:hover {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
    .product-review {
        width: 70%;
        height: 500px;
        margin: 0 auto;
    }
        .main div {
            height: 100%;
        }
    .body-container{
        max-height:600px;
    }
    .review-head {
        width: 100%;
        height: 20%;
        border: 1px solid #d5caca;
        background-color: #ffdfb5;
        font-weight: bold;
        border-radius: 5px;
        padding: 10px 10px;
    }
        .review-head button {
            border: 0;
            border-radius: 0;
            outline: 0;
            margin-left:20px;
            height:26px;
            color:white;
        }
    .review-items {
        width: 100%;
        max-height: 225px;
        border: 1px solid #8383a7;
        border-radius: 5px;
        padding: 0 10px 0 10px;
        overflow:auto;
    }
    #notify{
        width:70%;
        color:red;
        margin:0 auto;
    }

    #add-review{
        background-color:green;
    }
    #del-review{
        background-color:red;
    }
    #add-review:hover,
    #add-review:focus,
    #del-review:hover,
    #del-review:focus{
        background-color:black;
    }
</style>

BanTien/BanTien/Views/SanPhams/Edit.cshtml
@model BanTien.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chỉnh sửa sản phẩm</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTien)

        <div class="form-group">
            @Html.LabelFor(model => model.TenTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTien, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.TheLoai, "TheLoai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TheLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TheLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhMinhHoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhMinhHoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhMinhHoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BanTien/BanTien/Views/SanPhams/Index.cshtml
@model IEnumerable<BanTien.Models.SanPham>
<link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet" />



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<p>
    @Html.ActionLink("Thêm sản phẩm", "Create")
</p>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Tên sản phẩm
                        </th>

                        <th>
                            Số lượng
                        </th>
                        <th>
                            Đơn giá
                        </th>

                        <th>
                            Loại
                        </th>
                        <th>
                            Hình
                        </th>
                        <th>
                            Chức năng
                        </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>
                            Tên sản phẩm
                        </th>

                        <th>
                            Số lượng
                        </th>
                        <th>
                            Đơn giá
                        </th>

                        <th>
                            Loại
                        </th>
                        <th>
                            Hình
                        </th>
                        <th>
                            Chức năng
                        </th>
                    </tr>
                </tfoot>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenTien)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.SoLuong)
                            </td>
                            <td>
                                @item.DonGia.Value.ToString("0#,0") &#8363;
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LoaiTien.TenLoai)
                            </td>
                            <td>
                                <img style="width:50px; height:50px" src="@Html.DisplayFor(modelItem => item.AnhMinhHoa)" />
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.MaTien }) |
                                @Html.ActionLink("Details", "Details", new { id = item.MaTien }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.MaTien })
                            </td>
                        </tr>
                    }
                    </tbody>
            </table>
        </div>

    </div>
    </div>